### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by DennisAppelman** [xBourner/auto-dash#2]
unfortunatly the installation ends up in this error: 
custom element doesn’t exist: grid-layout.

how can i solve this?

<img width="453" alt="image" src="https://github.com/xBourner/auto-dash/assets/154830857/937bcada-0ff2-46db-b955-b2347b8a77bf">

**Comment by xBourner** [comment]
Did you install all custom cards from prerequisites? Especially the layout card?

**Comment by DennisAppelman** [comment]
removing the card and downloading again did solve it.
thanks for the advice!
